---
- name:
  block:
    - name: Copy Portus-compose
      copy:
        src: ../Portus-compose
        dest: /root/
        directory_mode: yes

    - name: Execute Docker-Compose
      raw: |
        cd /root/Portus-compose
        docker-compose up -d
