---
- name:
  block:
    - name: Copy Portus-compose
      file:
        src: ../../Portus-compse
        dest: /root/Portus-compose
        state: directory

    - name: Execute Docker-Compose
      raw: |
        cd /root/Portus-compose
        docker-compose up
